import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MastHead from "../components/masthead";
import AboutUs from "../components/aboutus";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>agency website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MastHead />
      <div className="text-black w-full container px-11 md:px-40 lg:mx-auto">
        <AboutUs />
      </div>
    </>
  );
};

export default Home;
